site_name: Kiwi Words
theme: mkdocs 
repo_url: https://github.com/Waikato/kiwiwords
google_analytics: ['UA-139965982-2', 'mkdocs.org']
site_description: Kiwi Words
nav:
    - Home: index.md
    - Māori Corpus: rmt_corpus.md
    - Loanwords: corpus.md
    - \#Covid19NZ: covidnz_corpus.md
    - NZE Lexicon: nze_lexicon.md
    - Māori English: maori_english.md